src/client/app/contributors/contributors.html
=> Removed pagination from contributors page

src/client/app/app.controller.js, src/client/app/search/search.directive.js, src/client/app/search/search.home.html, src/client/app/search/search.results.html, test/e2e/search-results.e2e.spec.js, test/page_objects/home.page.js, test/page_objects/results.page.js
=> Bug/cursor focus/396

src/client/app/advanced_search/advanced-search-controller.unit.spec.js, src/client/app/advanced_search/advanced-search.controller.js, src/client/app/core/search-service.js, test/e2e/advanced-search.e2e.spec.js, test/page_objects/results.page.js
Closes #413. I saw the update on this issue in my email and was able to tackle it fairly quickly.
- Fixed Advanced Search zombie filter bug. 
- Added unit and e2e tests to cover case. 
- Wrote utility function in SearchService to get default search opts object.
-----------------
PR Review
=> Fix Advanced Search zombie filter bug. 

test/page_objects/book-detail.page.js
Closes #411 
All tests should now pass...at least in Firefox :)
=> Fixed E2E test

src/client/app/search/search.facet_modal.html, src/client/app/search/search.results.html, src/client/css/app.css
=> Enhancement/facet modal responsive/329

src/client/app/advanced_search/advanced-search.controller.js, src/client/app/advanced_search/advanced-search.html, src/client/app/core/es-query-builder.js
Home button is also working now. Closes #382.
=> Bug/ie compatibility problems adv search/382

src/client/app/advanced_search/advanced-search.html, test/e2e/advanced-search.e2e.spec.js, test/page_objects/advanced.page.js
Closes #369 
Closes #298 
It seemed there are two issues--the form element seemed to have some bad structure, probably due to a merge between my and Kristen's code.  And then after some internet searching, it seems you have to set buttons used as dropdown inside a form to have type="button". Otherwise, the 'enter' button will have strange results and won't submit the form.
Reviewers:
=> Bug/adv enter regression/369

src/client/app/app.config.routing.js, src/client/app/core/search-res-parser.js, src/client/app/core/search-service.js, src/client/app/search/search.controller.js, src/client/app/search/search.results.html, src/client/css/app.css, test/e2e/search-results.e2e.spec.js, test/page_objects/results.page.js
Closes #423 -- indicate if a facet chip has zero limiting results
**Reviewers**
=> Enhancement/facet chip changes/423

src/client/app/search/search.results.html, test/e2e/search-results.e2e.spec.js, test/e2e/search-service.e2e.spec.js, test/page_objects/results.page.js
Closes #422.
-------------------
PR Review
=> Selected facets removed from sidebar, added passing tests

src/client/app/core/search-service.js
Closes #442 
This was a quick refactor which came out of a pull request review discussion on #440 
------------------
PR Review
=> Remove deprecated SearchService functions

src/client/app/search/search.home.html, src/client/css/app.css, test/e2e/search-home.e2e.spec.js, test/page_objects/home.page.js
Closes #452 
- See All Records Button back on HomePage.
- Worked with Kristen to set correct styles.
- Added E2E test for "See All Records" button.
-----------------
PR Approval
=> Re-add See All Records Button

src/client/app/partials/book-detail.html, src/client/app/search/search.home.html, src/client/css/app.css, test/e2e/search-home.e2e.spec.js, test/page_objects/home.page.js
=> Bug/item detail export button/473

src/client/app/advanced_search/advanced-search-controller.unit.spec.js, src/client/app/advanced_search/advanced-search.controller.js, src/client/app/app.config.routing.js, src/client/app/core/date-range.unit.spec.js, src/client/app/core/es-query-builder.js, src/client/app/core/search-service.js, src/client/app/core/search-service.unit.spec.js, src/client/app/saved_records/saved-records.html, src/client/app/search/search-controller.unit.spec.js, src/client/app/search/search.controller.js, src/client/app/search/search.results.html, src/server/api/views.py, test/e2e/search-results.e2e.spec.js, test/page_objects/results.page.js
=> Individual keyword chips in search bar for each new keyword search

src/client/app/partials/footer.html, src/client/css/app.css, test/e2e/search-home.e2e.spec.js, test/page_objects/home.page.js
=> Enhancement/footer links/78

src/client/css/app.css
=> Enhancement/animate results list/330

src/client/app/saved_records/saved-records.controller.js, test/e2e/saved-records.e2e.spec.js, test/page_objects/saved-records.page.js
=> Fixed Search History bug with clicking search term

src/client/app/app.config.routing.js, src/client/app/app.controller.js, src/client/app/app.module.js, src/client/app/home/home.controller.js, src/client/app/home/home.html, src/client/app/home/home.module.js, src/client/app/search/search.home.html, src/client/index.html, test/e2e/home.e2e.spec.js, test/page_objects/home.page.js
Closes #488 
- "See New Records" link on homepage takes use to all search results - sorted by Most Recent First.
- Added E2E tests.
- Refactored homepage code to live in own directory and module as per our convention.
------------
**PR Review**
=> See New Records link works

src/server/server/wsgi.py
=> Extended Python path in the wsgi.py file to avoid Apache deployment headaches

src/server/api/tests.py, src/server/api/views.py, test/e2e/search-results.e2e.spec.js
=> Bug/facet ampersand/535

config/local/app.env.config.json, src/client/app/app.config.routing.js, src/client/app/home/home.controller.js, test/e2e/home.e2e.spec.js
=> Enhancement/static title count/536

src/client/sitemap-index.xml
Closes #545 
@joshuago78 There are 4 new data files (from the 3 new institutions) here:
https://share.getty.edu/display/SDT/Data+Files+New+Contributors+for+Portal+Launch
=> Replaced existing sitemap files with updated ones.

src/client/app/book_detail/book-detail.html, src/client/app/search/search.results.html, test/e2e/book-detail.e2e.spec.js, test/e2e/search-results.e2e.spec.js
=> Fixed item detail and 'view digital item' links

src/client/app/app.config.routing.js, src/client/app/book_detail/book-detail.controller.js, src/client/app/book_detail/book-detail.html
Closes #551 
In the book detail state resolve I put the bookID in a data structure that the saved records button directive expected. That fixed the errors.
I also noticed that the book detail page was not getting updated when you saved/unsaved records from other tabs. I saw that the storage-event-listener had been removed from book_detail.html at some point, so I added that back in and now the book detail page gets updated.
=> Bug/saved records error/551

src/client/index.html
Do script includes for already-minified vendor code instead of the unminified code.
=> HOTFIX: Use minified vendor js for spin, smoothscroll

src/client/app/partials/dirPagination.tpl.html, src/client/app/search/search.results.html
=> Pagination bar display bugs

src/client/app/home/home.html, src/server/server/settings.py
=> Added new contributors to home page. Set feedback form email address

src/client/app/saved_records/saved-records.html, test/e2e/book-detail.e2e.spec.js, test/e2e/saved-records.e2e.spec.js, test/e2e/search-results.e2e.spec.js, test/page_objects/saved-records.page.js
Made some changes to other tests to reflect current es data. Ready to merge. Closes #559.
=> Bug/view digital item broken on saved records/559

src/client/index.html
=> Added Google Analytics to index.html

requirements.txt, src/server/server/settings.py
=> Added settings for using memcached with Django

src/client/sitemap-index.xml
=> Sitemaps updated with corrected Wolfenbuttel IDs

src/client/app/search/search.results.html
=> Bug/see all missing underline/567

docker_files/elasticsearch/Dockerfile
Closes #579 
@susanley already tried this and gave it a gold star - but @jfranco-gri can you please pull down and try too just to be sure?
=> Bug/analysis icu plugin/579

src/client/app/search/search.directive.js, src/client/app/search/search.results.html, src/client/css/app.css
Closes #479 
Should be fixed now. I tested this out on android and iPhone simulators and the keyboard doesn't pop up when clicking facet options. It still pops up when you click on the search bar.
=> Bug/mobile keyboard pops up/479

src/client/app/app.module.js, src/client/index.html
=> Google Analytics added

src/client/app/partials/feedback.html, src/client/css/app.css
closes #588. ready for review.
=> Enhancement/style feedback form/588

src/client/app/app.module.js, src/client/index.html
Reverts gri-is/portal#585
The original Pull Request causes almost all unit tests to fail.
=> Revert "Google Analytics added"

src/client/app/advanced_search/advanced-search.html, src/client/app/search/search-controller.unit.spec.js, src/client/app/search/search.controller.js, src/client/app/search/search.results.html, src/client/css/app.css, test/e2e/advanced-search.e2e.spec.js, test/e2e/search-results.e2e.spec.js, test/page_objects/results.page.js
=> Enhancement/adv search drop down/586

src/client/app/advanced_search/advanced-search.controller.js, src/client/app/advanced_search/advanced-search.html, src/client/app/advanced_search/constants.js, src/client/app/core/search-service.js, src/client/app/core/search-service.unit.spec.js, test/e2e/advanced-search.e2e.spec.js, test/page_objects/advanced.page.js
=> Enhancement/change keyword field in adv search/495

src/client/app/core/search-service.js, src/client/app/search/search-controller.unit.spec.js, src/client/app/search/search.controller.js, src/client/app/search/search.results.html, src/client/css/app.css, test/e2e/search-results.e2e.spec.js
=> Enhancement/refine adv drop down/600

src/client/robots.txt
=> Created robots.txt file

src/client/app/app.config.routing.js, src/client/app/core/constants.js, src/client/app/core/saved-records-service.js, src/client/app/core/saved-records.unit.spec.js, src/client/app/saved_records/saved-records.html, test/e2e/saved-records.e2e.spec.js
Closes #614 
I removed the "see all" searches from search history, but I haven't removed duplicate searches yet.
=> Enhancement/see all searches/614

src/client/app/book_detail/book-detail.html, src/server/api/es_functions.py, test/e2e/advanced-search.e2e.spec.js
=> Bug/adv search creator/619

src/client/app/book_detail/book-detail.html, test/e2e/book-detail.e2e.spec.js, test/page_objects/book-detail.page.js
=> Item detail page title now a link

src/client/app/book_detail/book-detail.html, src/client/css/app.css
=> View Digital Item button moved and styled

requirements.txt
=> Requirements.txt file changed to point to master funnel branch

src/client/app/book_detail/book-detail.controller.js, src/server/api/urls.py, test/e2e/search-results.e2e.spec.js
=> critical bug in API #644

src/client/app/book_detail/book-detail.controller.js, src/client/app/core/data-service.js, test/e2e/book-detail.e2e.spec.js
=> Export as JSON content fixed to omit unnecessary data

.gitignore, docker-compose.yml, logs/error.log, src/client/app/app.env.config.js, src/client/sitemap-index.xml, src/server/ingest/management/commands/process_contributions.py, src/server/ingest/tasks.py, src/server/ingest/tests.py
=> Enhancement/generate sitemap/661

src/client/css/app.css, src/client/index.html, src/server/server/settings.py, test/e2e/search-results.e2e.spec.js
Added CSS for date range slider to app.css file. Closes #673
=> Bug/restore rzslider/673

src/client/app/home/home.html, src/client/css/app.css
=> Announcement removed, styling adjusted

src/client/app/search/search.results.html, test/e2e/search-results.e2e.spec.js, test/page_objects/results.page.js
=> Added publication info to brief display with tests
